# Generated by Django 5.1.4 on 2026-09-12 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('ORDERING', 'Ordering'), ('PREPARING', 'Preparing'), ('READY', 'Ready')], default='AVAILABLE', max_length=20)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cafes.cafe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cafe', 'number'), name='uq_table_cafe_number')],
            },
        ),
    ]
