# Generated by Django 5.1.4 on 2026-09-12 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_vpa', models.CharField(blank=True, max_length=120, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('order_seq', models.PositiveIntegerField(default=1047)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
